services:
  friesenradar:
    image: ghcr.io/regover13/friesenradar:latest
    ports:
      - "127.0.0.1:8091:8091"
    volumes:
      - ./data:/opt/friesenradar/data
    env_file: config.env
    restart: unless-stopped
